#include <Arduino.h>

struct {
	String name;
	uint32_t size;
} static const SDSizes[] PROGMEM = {
		{ "/WheelsonRC/game.properties",             133 },
		{ "/WheelsonRC/data/mini_bb.raw",            180 },
		{ "/WheelsonRC/data/wheel-crossed.raw",      9800 },
		{ "/WheelsonRC/data/background.raw.hs",      540 },
		{ "/WheelsonRC/data/mini_wh.raw",            180 },
		{ "/WheelsonRC/data/wheel.raw",              9800 },
		{ "/WheelsonRC/WheelsonRC.raw",              8192 },
		{ "/WheelsonRC/WheelsonRC.bin",              1851088 },
		{ "/CastleJump/Music/Game.aac",              1097190 },
		{ "/CastleJump/Music/Menu.aac",              583334 },
		{ "/CastleJump/Castle.raw",                  8192 },
		{ "/CastleJump/game.properties",             175 },
		{ "/CastleJump/data/Pod160x10.raw",          3200 },
		{ "/CastleJump/data/Homescreen.raw.hs",      3439 },
		{ "/CastleJump/data/heart.hpp.g565",         744 },
		{ "/CastleJump/data/GameOver160x128.raw.hs", 597 },
		{ "/CastleJump/data/PodLava160x10.g565.hs",  866 },
		{ "/CastleJump/data/Highscore.raw.hs",       3131 },
		{ "/CastleJump/CastleJump.bin",              1165184 },
		{ "/Anarch/game.properties",                 104 },
		{ "/Anarch/Anarch.raw",                      8192 },
		{ "/Anarch/Anarch.bin",                      1101056 },
		{ "/.ByteBoi",                               1 },
		{ "/Bonk/Music/Game.aac",                    1072105 },
		{ "/Bonk/Music/Menu.aac",                    836904 },
		{ "/Bonk/Bonk.bin",                          1096816 },
		{ "/Bonk/game.properties",                   133 },
		{ "/Bonk/Bonk.raw",                          8192 },
		{ "/Blocks/Music/Twister.aac",               1400261 },
		{ "/Blocks/Music/GameOver.aac",              429571 },
		{ "/Blocks/Blocks.bin",                      1106256 },
		{ "/Blocks/game.properties",                 129 },
		{ "/Blocks/Blocks.raw",                      8192 },
		{ "/Blocks/data/BlocksMenuBg.raw.hs",        590 },
		{ "/Invaderz/Music/Game.aac",                1566273 },
		{ "/Invaderz/Music/Menu.aac",                894638 },
		{ "/Invaderz/Music/GameOver.aac",            429571 },
		{ "/Invaderz/Invaderz.bin",                  1109792 },
		{ "/Invaderz/game.properties",               159 },
		{ "/Invaderz/Invaderz.raw",                  8192 },
		{ "/Snake/Music/Game.aac",                   985350 },
		{ "/Snake/Music/Menu.aac",                   1319579 },
		{ "/Snake/game.properties",                  149 },
		{ "/Snake/Snake.bin",                        1104176 },
		{ "/Snake/Snake.raw",                        8192 },
		{ "/SpaceRocks/Music/Game.aac",              1746491 },
		{ "/SpaceRocks/Music/Menu.aac",              882397 },
		{ "/SpaceRocks/Music/GameOver.aac",          429571 },
		{ "/SpaceRocks/Rocks.raw",                   8192 },
		{ "/SpaceRocks/game.properties",             137 },
		{ "/SpaceRocks/SpaceRocks.bin",              1306560 }
};
